import { BookmarkIcon, StarIcon, ChatBubbleLeftRightIcon } from '@heroicons/react/24/solid';

export const APP_NAME = 'BUFET';

export const links = [
  {
    id: 1,
    name: 'instagram',
    href: 'https://www.instagram.com/bufetua',
    img: '/icons/bufet_instagram_icon.svg',
  },
  {
    id: 2,
    name: 'facebook',
    href: 'https://www.facebook.com/bufetua',
    img: '/icons/bufet_facebook_icon.svg',
  },
  {
    id: 3,
    name: 'app_store',
    href: 'https://apps.apple.com/ua/app/bufet/id6737837528?l=ru',
    img: '/icons/app_store_icon.svg',
  },
  {
    id: 4,
    name: 'google_play',
    href: 'https://play.google.com/store/apps/details?id=com.bufet.stage&hl=uk&pli=1',
    img: '/icons/google_play_icon.svg',
  },
];

export const info = [
  {
    id: 1,
    title: 'Найближчий BUFET',
    description:
      'Щороку ми займаємося упорядкуванням території поблизу піцерій BUFET, аби прогулюючись, Ви могли трохи відпочити й присісти на лавочку біля нашого закладу, а влітку насолодитися прохолодою в тіні дерев.',
    icon: BookmarkIcon,
  },
  {
    id: 2,
    title: 'Наше меню',
    description:
      'Основна страва, яку Вам запропонують у мережі BUFET – це піца. Ми готуємо за власними фірмовими рецептами й на будь-який смак. Тут свою улюблену піцу знайдуть і шанувальники ситних страв, і ті, хто дбає про фігуру й здоровий спосіб життя та рахує калорії.',
    icon: StarIcon,
  },
  {
    id: 3,
    title: 'Відгуки',
    description: 'Будемо раді коментарям щодо роботи мережі BUFET та побажанням і подякам.',
    icon: ChatBubbleLeftRightIcon,
  },
];

export const news = [
  {
    id: 1,
    title: 'Bolt Food доставляє продукцію із наших закладів',
    body: 'Ми знаємо, що іноді обставини складаються так що ви не можете прийти до нас. Тому ми співпрацюємо з bolt food. Для оформлення замовлення необхідно завантажити мобільний додаток та зробити в ньому замовлення. А ми все одно чекатимемо вас у гості.',
    img: '/img/news/bolt-food.png',
    author: 'Ольга Филенко',
    category: 'Новини',
    date: '26.07',
  },
  {
    id: 2,
    title: 'Додаток для замовлення працює!',
    body: 'З 1 березня 2025 року ми змінили додаток для попереднього замовлення. Новий додаток — нове життя попереднього замовлення. Наразі ми тестуємо оплату онлайн лише на одному закладі, але у майбутньому підключемо в усіх. Будь ласка, допоможіть нам протестувати новий додаток, чекаємо на зворотній зв’язок.',
    img: '/img/news/dodatok.jpg',
    author: 'BUFET',
    category: 'Новини',
    date: '11.03',
  },
  {
    id: 3,
    title: 'Ми працюємо',
    body: 'Адреси закладів, які вже працюють: 1. Полтавський шлях 126 2. Вул. Любові Малої 24 3. Пр-т. Гагаріна 177 4. Вул. Культури 23 5. Пр-т. Архітектора Альошина 19 6. Вул. Сумська 41 7. Пр-т. Героїв Харкова 256 8. Пр-т. Незалежності 5а 9. Вул. Пушкінська 92 10. Пр-т. Науки 38 11. Вул. ...',
    img: '/img/news/my-vidkruti.jpg',
    author: 'BUFET',
    category: 'Новини',
    date: '28.07',
  },
  {
    id: 4,
    title: 'Все буде Україна',
    body: 'Ми теж сумували. Ми теж ховалися у сховищах. Продовжували готувати їжу для ЗСУ, тероборони та цивільних. Дякуємо нашим співробітникам за їхню сміливість з 24 лютого і до цього дня. Ми не будемо писати про втрати чи труднощі — ми працюємо далі.',
    img: '/img/news/vaucher.png',
    author: 'BUFET',
    category: 'Новини',
    date: '25.05',
  },
  {
    id: 5,
    title: 'Розіграш в Instagram',
    body: 'Умови участі: 1) Бути підписаним на @bufetua. 2) Поставити лайк на публікацію з розіграшем. 3) Відмітити друга у коментарях. Докладні правила участі вказані у пості. Розіграш проводиться лише на території м. Харкова.',
    img: '/img/news/drawer.jpg',
    author: 'BUFET',
    category: 'Новини',
    date: '06.01',
  },
  {
    id: 6,
    title: 'Чудова кава',
    body: 'Щорічне тестування ранкової кави стало нашою традицією. Спробуй безкоштовно будь-яку каву 200 мл та оціни роботу бариста. Ми чекаємо на твій зворотній зв’язок у закладах або соцмережах.',
    img: '/img/news/card.jpg',
    author: 'BUFET',
    category: 'Новини',
    date: '05.01',
  },
  {
    id: 7,
    title: 'Неправильна утилізація батарейок несе серйозні проблеми',
    body: 'Батарейки після використання можуть бути небезпечними при пошкодженні корпусу чи неправильних умовах зберігання. Потрапляючи на смітник, вони піддаються впливу середовища та завдають шкоди екології.',
    img: '/img/news/battery.jpg',
    author: 'BUFET',
    category: 'Новини',
    date: '23.12',
  },
  {
    id: 8,
    title: 'Участь у проекті Картка Харків’янина',
    body: 'Картка харків’янина — унікальний проєкт, який замінює E-ticket, дає можливість безкоштовно відвідати зоопарк та отримувати знижки. Буфет — 100% харківська мережа, і ми підтримуємо все, що робить місто кращим.',
    img: '/img/news/card.jpg',
    author: 'BUFET',
    category: 'Новини',
    date: '15.12',
  },
  {
    id: 9,
    title: 'Еко-рух який ми підтримуємо',
    body: 'В Україні набув чинності закон про обмеження обігу пластикових пакетів. Нам подобаються еко-рухи, і це літо ми провели разом із чудовими волонтерами, підтримуючи ініціативи зі зменшення пластику.',
    img: '/img/news/eco.jpg',
    author: 'BUFET',
    category: 'Новини',
    date: '10.12',
  },
  {
    id: 10,
    title: 'Розіграш в Instagram',
    body: 'Умови участі: бути підписаним на @bufetua, поставити лайк та відмітити друга. Розіграш проводиться лише у Харкові в мережі BUFET. Повні правила — у пості.',
    img: '/img/news/drawer.jpg',
    author: 'BUFET',
    category: 'Новини',
    date: '11.09',
  },
  {
    id: 11,
    title: 'Розіграш в Instagram',
    body: 'Умови участі: підписка на @bufetua, лайк та коментар з другом. Розіграш проходить у м. Харків. Деталі — у правилах заходу.',
    img: '/img/news/drawer.jpg',
    author: 'BUFET',
    category: 'Новини',
    date: '17.05',
  },
  {
    id: 12,
    title: 'О-о-окрошка',
    body: 'Температура зростає — час для окрошки! У складі: куряче філе, свіжі огірки, яйця, картопля, кріп, цибуля, сметана, майонез, гірчиця, лимонна кислота. Чекає на тебе у всіх закладах BUFET!',
    img: '/img/news/okroshka.jpg',
    author: 'BUFET',
    category: 'Новини',
    date: '12.05',
  },
];

export const promo = [
  { id: 1, name: 'eko', img: '/img/promo/eko.jpg' },
  { id: 2, name: 'app', img: '/img/promo/app.jpg' },
  { id: 3, name: 'bolt', img: '/img/promo/bolt.jpg' },
  { id: 4, name: 'open', img: '/img/promo/open.jpg' },
  { id: 5, name: 'price', img: '/img/promo/price.jpg' },
];

export const nav = [
  { id: 1, name: 'головна', href: '/', hasDropdown: false },
  { id: 2, name: 'меню', href: '/menu', hasDropdown: true },
  { id: 3, name: 'знайти bufet', href: '/find', hasDropdown: false },
  { id: 4, name: 'новини', href: '/news', hasDropdown: false },
  { id: 5, name: 'зворотнiй зв`язок', href: '/feedback', hasDropdown: false },
  { id: 6, name: 'вiдео', href: '/video', hasDropdown: false },
  { id: 7, name: 'про нас', href: '/about', hasDropdown: false },
  { id: 8, name: 'кар`ера', href: '/career', hasDropdown: false },
  { id: 9, name: 'партнерам', href: '/suppliers', hasDropdown: false },
];

export const product_categories = [
  {
    id: 1,
    title: 'Піца',
    href: '/pizza',
    slug: 'pizza',
    description: 'Смачна піца від BUFET',
    products: [
      {
        id: 1,
        title: ' Піца «Мексиканська»',
        description: 'Наша нова велика кругла пiца.',
        ingredients: [
          'тонка основа',
          'запечене куряче стегно',
          'мексиканський соус (гострий)',
          'кукурудза консервована',
          'помідори',
          'твердий сир',
        ],
        slug: 'mexican',
        price: 170,
        weight: 540,
        ccal: 220,
        preview: '/img/products/pizzas/meksika-pizza_category_new.jpg',
        product: '/img/products/pizzas/product/meksika-pizza_product_new.jpg',
      },
      {
        id: 2,
        title: ' Піца «М`ясний мiкс» (на тонкому тiстi)',
        slug: 'meat_mix',
        price: 160,
        description: 'Наша нова велика кругла пiца.',
        ingredients: [
          'Тонка основа тіста',
          'Салямі сирокопчена',
          'Грудинка варено-копчена',
          'Балик варено-копчений',
          'Твердий сир',
          'Болгарський перець',
          'Томатний соус',
        ],
        weight: 450,
        ccal: 272,
        preview: '/img/products/pizzas/myaso_category_new.jpg',
        product: '/img/products/pizzas/product/myaso_product_new.jpg',
      },
      {
        id: 3,
        title: ' Піца «Цезар NEW» (на тонкому тiстi)',
        slug: 'caesar',
        price: 160,
        description: 'Наша нова велика кругла пiца.',
        ingredients: [
          'Тонка основа тіста',
          'Куряче філе',
          'Грудинка свиняча варено-копчена',
          'Твердий сир',
          'Сир Пармезан',
          'Помідори',
          'Вершковий соус з часником та спеціями',
        ],
        weight: 440,
        ccal: 282,
        preview: '/img/products/pizzas/cesar_category_new.jpg',
        product: '/img/products/pizzas/product/cesar_product_new.jpg',
      },
      {
        id: 4,
        title: ' Піца «Чотири сира» (на тонкому тiстi) ',
        slug: '4cheese',
        price: 160,
        description: '',
        ingredients: [
          'Тонка основа',
          'Вершковий соус на основу сиру Філадельфія',
          'Твердий сир',
          'Сир Пармезан',
          'Дорблю',
        ],
        weight: 400,
        ccal: 313,
        preview: '/img/products/pizzas/4-syra_category_new.jpg',
        product: '/img/products/pizzas/product/4-syra_product_new.jpg',
      },
      {
        id: 5,
        title: ' Піца «Баварська»',
        slug: 'bavarian',
        price: 140,
        description:
          'Унікальна відмінність піци «Баварська» – це відсутність у ній майонезу! Приготована піца на тонкому тісті.',
        ingredients: [
          'Ковбаса сирокопчена',
          'Огірки солоні',
          'Помідор',
          'Сир',
          'Олива',
          'Томатный соус',
          'Спеції “Трави Італії”',
        ],
        weight: 500,
        ccal: 251,
        preview: '/img/products/pizzas/bavarska-1.jpg',
        product: '/img/products/pizzas/product/bavarska-2.jpg',
      },
      {
        id: 6,
        title: ' Піца «Фiтнес»',
        slug: 'fitnes',
        price: 140,
        description:
          'Унікальність піци «Фітнес» – це відсутність у ній майонезу! За рахунок ідеального підбору легкого соусу, соковитого перцю й ніжного курячого філе вона не тільки корисна, але й має бездоганний смак. Навіть найсправжнісінький гурман оцінить її належним чином!',
        ingredients: [
          'Курка',
          'Сир',
          'Перець болгарський',
          'Помідор',
          'Кріп',
          'Томатныий соус',
          'Солодкий соус чилі',
        ],
        weight: 530,
        ccal: 207,
        preview: '/img/products/pizzas/fitnes-1.jpg',
        product: '/img/products/pizzas/product/fitnes-2.jpg',
      },
      {
        id: 7,
        title: ' Піца «Фiрмова»',
        slug: 'firmova',
        price: 150,
        description:
          'Можна казати багато, але назва каже сама за себе. Піца «Фірмова» від нашого кухаря – спеціально для Вас!',
        ingredients: ['Курка', 'Шинка', 'Майонез', 'Сир', 'Печериці', 'Маслини', 'Томатний соус'],
        weight: 540,
        ccal: 218,
        preview: '/img/products/pizzas/firmennaya-1.jpg',
        product: '/img/products/pizzas/product/firmennaya-2.jpg',
      },
      {
        id: 8,
        title: ' Піца «Салямi»',
        slug: 'salami',
        price: 140,
        description:
          'Iдеальний перекус: засмажені ковбасні палички з солоними огірочками – це те, що робить піцу «Салямі» незабутньою!',
        ingredients: [
          'Салямі',
          'Томатний соус із часником',
          'Огірки солені',
          'Кріп',
          'Майонез',
          'Сир',
        ],
        weight: 470,
        ccal: 269,
        preview: '/img/products/pizzas/salyami-1.jpg',
        product: '/img/products/pizzas/product/salyami-2.jpg',
      },
      {
        id: 9,
        title: ' Піца «Курка з ананасом»',
        slug: 'chicken_pineapple',
        price: 130,
        description:
          'Курка й ананас – чудове поєднання для піци, що подарує Вам позитивні емоції, а головне – втамує голод!',
        ingredients: ['Курка', 'Ананас', 'Томатний соус', 'Майонез', 'Сир'],
        weight: 530,
        ccal: 224,
        preview: '/img/products/pizzas/kurica-s-ananasom-1.jpg',
        product: '/img/products/pizzas/product/kurica-s-ananasom-2.jpg',
      },
      {
        id: 10,
        title: ' Піца «Курка з грибами»',
        slug: 'chicken_mushrooms',
        price: 130,
        description:
          'Iдеальний перекус: засмажені ковбасні палички з солоними огірочками – це те, що робить піцу «Салямі» незабутньою!',
        ingredients: ['Курка', 'Печерицi', 'Томатний соус', 'Майонез', 'Сир'],
        weight: 470,
        ccal: 269,
        preview: '/img/products/pizzas/kurica-s-gribami-1.jpg',
        product: '/img/products/pizzas/product/kurica-s-gribami-2.jpg',
      },
      {
        id: 11,
        title: ' Піца «З грибами»',
        slug: 'mushrooms',
        price: 130,
        description:
          'Аромат грибів огорне Вас відчуттям весни й тепла та нагадає незабутні моменти й подарує насолоду смаком.',
        ingredients: [
          'Тонка основа',
          'Гриби печериці',
          'Болгарський перець',
          'Сир',
          'Томатний соус',
          'Майонез',
        ],
        weight: 530,
        ccal: 196,
        preview: '/img/products/pizzas/gryby_category.jpg',
        product: '/img/products/pizzas/product/gryby_product.jpg',
      },
      {
        id: 12,
        title: ' Піца «З шинкою»',
        slug: 'ham',
        price: 130,
        description:
          'Ох вже ця ковбаска, пишна основа й нічого зайвого. Піца з шинкою – відмінне рішення для закуски.',
        ingredients: ['Шинка', 'Томатний соус', 'Майонез', 'Сир'],
        weight: 480,
        ccal: 246,
        preview: '/img/products/pizzas/s-vetchinoj-1.jpg',
        product: '/img/products/pizzas/product/s-vetchinoj-2.jpg',
      },

      {
        id: 13,
        title: ' Піца «М`яcна»',
        slug: 'meat',
        price: 150,
        description:
          'Ви куштували нашу м’ясну піцу?! Якщо так, тоді ви точно помітили – вона не тільки соковита, але й смачна! Легкий часниковий соус підкреслює смак яловичини, а зелень із помідорами радує око!',
        ingredients: [
          'Яловичина',
          'Помідор',
          'Томатний соус із часником',
          'Майонез',
          'Сир',
          'Кріп',
        ],
        weight: 480,
        ccal: 233,
        preview: '/img/products/pizzas/myasnaya-1.jpg',
        product: '/img/products/pizzas/product/myasnaya-2.jpg',
      },
    ],
  },
  {
    id: 2,
    title: 'Салати',
    href: '/salads',
    slug: 'salads',
    description: 'Салати від BUFET',
    products: [
      {
        id: 1,
        title: 'Боул з тунцем та кiноа',
        slug: 'boul',
        price: 95,
        description:
          'Свіжий боул з тунцем та кiноа, багатий на білок і корисні мікроелементи. Ідеально підійде для легкої та поживної трапези.',
        ingredients: ['Тунець', 'Кіноа', 'Огірки', 'Помідори', 'Авокадо', 'Соус на основі йогурту'],
        weight: 350,
        ccal: 220,
        preview: '/img/products/salats/boul_category.jpg',
        product: '/img/products/salats/product/boul_product.png',
      },
      {
        id: 2,
        title: 'Салат цезар з соусом цезар',
        slug: 'caesar_salad',
        price: 80,
        description:
          'Класичний салат Цезар з соковитою куркою, хрусткими крутонами та ніжним соусом Цезар.',
        ingredients: ['Курка', 'Салат Романо', 'Крутони', 'Пармезан', 'Соус Цезар'],
        weight: 300,
        ccal: 250,
        preview: '/img/products/salats/cezar_i_cezar_category.jpg',
        product: '/img/products/salats/product/cezar_i_cezar_product.jpg',
      },
      {
        id: 3,
        title: 'Салат цезар з соусом пiкантний',
        slug: 'caesar_salad_pikantniy',
        price: 80,
        description:
          'Салат Цезар з пікантним соусом для тих, хто любить трішки гостроти та насиченого смаку.',
        ingredients: ['Курка', 'Салат Романо', 'Крутони', 'Пармезан', 'Пікантний соус'],
        weight: 300,
        ccal: 260,
        preview: '/img/products/salats/cezar_i_pikantnyj_category.jpg',
        product: '/img/products/salats/product/cezar_i_pikantnyj_product.jpg',
      },
      {
        id: 4,
        title: 'Салат Весняний',
        slug: 'vesnyaniy',
        price: 45,
        description:
          'Легкий та свіжий весняний салат із сезонних овочів, відмінний вибір для легкого обіду.',
        ingredients: ['Огірки', 'Помідори', 'Салатні листя', 'Редис', 'Оливкова олія'],
        weight: 250,
        ccal: 120,
        preview: '/img/products/salats/salat-vesenii_category.jpg',
        product: '/img/products/salats/product/salat-vesenii_product.jpg',
      },
      {
        id: 5,
        title: 'Салат Столичний',
        slug: 'stolichniy',
        price: 50,
        description:
          'Класичний салат “Столичний” з вареною ковбасою, овочами та майонезом — смачно та ситно.',
        ingredients: ['Ковбаса варена', 'Яйця', 'Огірки', 'Картопля', 'Морква', 'Майонез'],
        weight: 300,
        ccal: 270,
        preview: '/img/products/salats/salat-stolichny_category.jpg',
        product: '/img/products/salats/product/salat-stolichny_product.jpg',
      },
      {
        id: 6,
        title: 'Салат Фантазiя',
        slug: 'fantasy',
        price: 50,
        description:
          'Салат Фантазія — яскраве поєднання овочів і курячого філе з ніжним соусом для особливого смаку.',
        ingredients: ['Курка', 'Салатні листя', 'Помідори', 'Огірки', 'Сир', 'Соус майонезний'],
        weight: 320,
        ccal: 240,
        preview: '/img/products/salats/salat-fantaziya_category.jpg',
        product: '/img/products/salats/product/salat-fantaziya_category.jpg',
      },
      {
        id: 7,
        title: 'Салат Оселедець пiд шубою',
        slug: 'herring_salad',
        price: 50,
        description:
          'Традиційний салат Оселедець під шубою з оселедцем, овочами та майонезом — класика для святкового столу.',
        ingredients: ['Оселедець', 'Картопля', 'Морква', 'Буряк', 'Майонез'],
        weight: 350,
        ccal: 280,
        preview: '/img/products/salats/salat-shyba_category.jpg',
        product: '/img/products/salats/product/salat-shyba_product.jpg',
      },
    ],
  },
  {
    id: 3,
    title: 'Першi страви',
    href: '/first_dishes',
    slug: 'first_dishes',
    description: 'Домашнi супчики від BUFET',
    products: [
      {
        id: 1,
        title: 'Солянка м`ясна',
        slug: 'solyanka',
        price: 75,
        description:
          'Класична м’ясна солянка з різних видів м’яса, з насиченим смаком та легкою кислинкою від огірків і лимона.',
        ingredients: [
          'Яловичина',
          'Свинина',
          'Ковбаса',
          'Мариновані огірки',
          'Цибуля',
          'Лимон',
          'Оливки',
          'Томатна паста',
        ],
        weight: 400,
        ccal: 280,
        preview: '/img/products/first/salanka_category.jpg',
        product: '/img/products/first/salanka_category.jpg',
      },
      {
        id: 2,
        title: 'Рамен',
        slug: 'ramen',
        price: 65,
        description:
          'Смачний японський рамен з ніжним бульйоном, локшиною та соковитими овочами. Ідеально зігріває в холодну погоду.',
        ingredients: [
          'Локшина',
          'Бульйон курячий',
          'Курка',
          'Яйце',
          'Зелена цибуля',
          'Морква',
          'Капуста',
          'Соєвий соус',
        ],
        weight: 350,
        ccal: 260,
        preview: '/img/products/first/ramen_category.jpg',
        product: '/img/products/first/ramen_category.jpg',
      },
      {
        id: 3,
        title: 'Окрошка з куркою',
        slug: 'okroshka',
        price: 65,
        description:
          'Легка літня окрошка з курячим філе, свіжими овочами та кефіром. Освіжаюча та ситна страва.',
        ingredients: [
          'Курка',
          'Картопля',
          'Огірки',
          'Редис',
          'Зелень (кріп, петрушка)',
          'Яйця',
          'Кефір',
          'Гірчиця',
        ],
        weight: 300,
        ccal: 180,
        preview: '/img/products/first/okroshka-category.jpg',
        product: '/img/products/first/okroshka-category.jpg',
      },
    ],
  },
  {
    id: 4,
    title: 'Други страви',
    href: '/second_dishes',
    slug: 'second_dishes',
    description: 'Смачнi гарнiри та м`яснi страви від BUFET',
    products: [
      {
        id: 1,
        title: 'Спагетi Болоньезе',
        slug: 'spageti_bolonese',
        price: 80,
        description:
          'Класичні італійські спагеті з ніжним м’ясним соусом болоньєзе, присмачені пармезаном.',
        ingredients: [
          'Спагеті',
          'Яловичина',
          'Помідори',
          'Цибуля',
          'Морква',
          'Часник',
          'Сир Пармезан',
          'Оливкова олія',
        ],
        weight: 400,
        ccal: 350,
        preview: '/img/products/second/balaneze_category_new.jpg',
        product: '/img/products/second/product/balaneze_product_new.jpg',
      },
      {
        id: 2,
        title: 'Фиш бургер (естонский хек)',
        slug: 'fishburger',
        price: 95,
        description:
          'Соковитий бургер з естонським хеком, свіжими овочами та соусом тар-тар у м’якій булочці.',
        ingredients: ['Хек', 'Булочка', 'Листя салату', 'Помідор', 'Сир', 'Соус тар-тар', 'Цибуля'],
        weight: 250,
        ccal: 320,
        preview: '/img/products/second/fishburger_category_new.jpg',
        product: '/img/products/second/product/fishburger_product_new.jpg',
      },
      {
        id: 3,
        title: 'Шведськi Фрiкадельки',
        slug: 'frikadelki',
        price: 75,
        description:
          'Ніжні шведські фрикадельки зі сметанним соусом та ароматними спеціями, подаються з картоплею.',
        ingredients: [
          'Яловичина',
          'Свинина',
          'Цибуля',
          'Сметана',
          'Яйце',
          'Панірувальні сухарі',
          'Спеції',
        ],
        weight: 350,
        ccal: 300,
        preview: '/img/products/second/frikadelki_category.jpg',
        product: '/img/products/second/product/frikadelki_product.jpg',
      },
      {
        id: 4,
        title: 'Картопля по-селянскi',
        slug: 'potato_wedges',
        price: 50,
        description:
          'Соковита картопля по-селянськи з ароматними спеціями та золотистою скоринкою.',
        ingredients: ['Картопля', 'Олія', 'Сіль', 'Перець', 'Паприка', 'Часник'],
        weight: 300,
        ccal: 250,
        preview: '/img/products/second/selanski_category.jpg',
        product: '/img/products/second/product/selanski_product-.jpg',
      },
      {
        id: 5,
        title: 'Чiзбургер з яловичиною та беконом',
        slug: 'cheeseburger_beef_beacon',
        price: 100,
        description:
          'Соковитий чізбургер з яловичиною, хрустким беконом, сиром чеддер та свіжими овочами.',
        ingredients: [
          'Булочка',
          'Яловичина',
          'Бекон',
          'Сир Чеддер',
          'Листя салату',
          'Помідор',
          'Соус майонез',
        ],
        weight: 300,
        ccal: 400,
        preview: '/img/products/second/cheeseburger-beef-bekon_category_new.jpg',
        product: '/img/products/second/product/cheeseburger-beef-bekon_product_new.jpg',
      },
      {
        id: 6,
        title: 'Ланч з картоплею',
        slug: 'lunch',
        price: 80,
        description:
          'Смачний ланч з куркою або яловичиною, поданий з картоплею та свіжими овочами.',
        ingredients: ['Курка/Яловичина', 'Картопля', 'Овочі', 'Соус', 'Зелень', 'Олія'],
        weight: 350,
        ccal: 320,
        preview: '/img/products/second/lanch_category_new.jpg',
        product: '/img/products/second/product/lanch_product_new.jpg',
      },
      {
        id: 7,
        title: 'Нагетси',
        slug: 'nuggets',
        price: 85,
        description:
          'Хрусткі курячі нагетси з ніжною серединкою, ідеальні для швидкого перекусу або обіду.',
        ingredients: ['Курка', 'Панірувальні сухарі', 'Яйце', 'Олія', 'Спеції'],
        weight: 200,
        ccal: 250,
        preview: '/img/products/second/nagetsy_category_new.jpg',
        product: '/img/products/second/product/nagetsy_product_new.jpg',
      },
      {
        id: 8,
        title: 'Чiзбургер з куркою',
        slug: 'cheeseburger_chicken',
        price: 90,
        description:
          'Соковитий чізбургер з курячою котлетою, сиром та свіжими овочами, подається з соусом.',
        ingredients: ['Булочка', 'Курка', 'Сир Чеддер', 'Листя салату', 'Помідор', 'Соус'],
        weight: 300,
        ccal: 350,
        preview: '/img/products/second/cheeseburger-chicken_category_new-1.jpg',
        product: '/img/products/second/product/cheeseburger-chicken_product_new-1.jpg',
      },
      {
        id: 9,
        title: 'Чiзбургер з яловичиною',
        slug: 'cheeseburger_beef',
        price: 100,
        description:
          'Класичний чізбургер з яловичою котлетою, сиром та свіжими овочами у м’якій булочці.',
        ingredients: ['Булочка', 'Яловичина', 'Сир Чеддер', 'Листя салату', 'Помідор', 'Соус'],
        weight: 300,
        ccal: 380,
        preview: '/img/products/second/cheeseburger-beef_category_new-1.jpg',
        product: '/img/products/second/product/cheeseburger-beef_product_new-1.jpg',
      },
      {
        id: 10,
        title: 'Локчина Под-Тай',
        slug: 'podtai',
        price: 80,
        description:
          'Тайська локшина з овочами, куркою та соусом под-тай, ароматна та пікантна страва.',
        ingredients: ['Локшина', 'Курка', 'Овочі', 'Соус Под-Тай', 'Кінза', 'Арахіс'],
        weight: 350,
        ccal: 300,
        preview: '/img/products/second/pad-tay_category-1.jpg',
        product: '/img/products/second/product/pad-tay_product1.jpg',
      },
      {
        id: 11,
        title: 'Буф Ролл',
        slug: 'bufroll',
        price: 85,
        description: 'Рол з куркою, овочами та соусом, ідеальний для швидкого перекусу чи обіду.',
        ingredients: ['Лаваш', 'Курка', 'Овочі', 'Соус', 'Сир'],
        weight: 250,
        ccal: 280,
        preview: '/img/products/second/BUFROLL_category.jpg',
        product: '/img/products/second/product/BUFROLL_product.jpg',
      },
      {
        id: 12,
        title: 'Картопля фрi Air',
        slug: 'french_fries',
        price: 50,
        description:
          'Золотисті картопляні фрі, хрусткі зовні та ніжні всередині, ідеальні до будь-якої страви.',
        ingredients: ['Картопля', 'Олія', 'Сіль', 'Перець'],
        weight: 200,
        ccal: 220,
        preview: '/img/products/second/french_fries_category.jpg',
        product: '/img/products/second/product/french_fries_product.jpg',
      },
      {
        id: 13,
        title: 'Гратен яловичий',
        slug: 'graten',
        price: 80,
        description:
          'Соковитий гратен з яловичиною, сиром та вершковим соусом, запечений до золотистої скоринки.',
        ingredients: ['Яловичина', 'Картопля', 'Сир', 'Вершковий соус', 'Спеції'],
        weight: 350,
        ccal: 360,
        preview: '/img/products/second/graten_category.jpg',
        product: '/img/products/second/product/graten_product.jpg',
      },
    ],
  },
  {
    id: 5,
    title: 'Соуси',
    href: '/souses',
    slug: 'souses',
    description: 'Пікантний та неповторний смак стравам додадуть соуси від BUFET',
    products: [
      {
        id: 1,
        title: 'Соус Цезар',
        slug: 'caesar_sause',
        price: 10,
        description: 'Класичний соус Цезар на основі майонезу з анчоусами, часником і пармезаном.',
        ingredients: ['Майонез', 'Анчоуси', 'Часник', 'Сир Пармезан', 'Лимонний сік', 'Спеції'],
        weight: 50,
        ccal: 120,
        preview: '/img/products/souses/cezar_sous_category.jpg',
        product: '/img/products/souses/cezar_sous_category.jpg',
      },
      {
        id: 2,
        title: 'Часниковий соус',
        slug: 'garlic_sause',
        price: 10,
        description: 'Ніжний соус з часником, олією та спеціями, ідеальний до м’яса та піци.',
        ingredients: ['Часник', 'Олія', 'Майонез', 'Сметана', 'Сіль', 'Перець'],
        weight: 50,
        ccal: 100,
        preview: '/img/products/souses/czasnok_category.jpg',
        product: '/img/products/souses/czasnok_category.jpg',
      },
      {
        id: 3,
        title: 'Кетчуп',
        slug: 'ketchap_sause',
        price: 10,
        description: 'Класичний томатний кетчуп з натуральних помідорів з легкою кислинкою.',
        ingredients: ['Помідори', 'Цукор', 'Сіль', 'Оцет', 'Спеції'],
        weight: 50,
        ccal: 80,
        preview: '/img/products/souses/ketchup_category-1-1.jpg',
        product: '/img/products/souses/ketchup_category-1-1.jpg',
      },
      {
        id: 4,
        title: 'Соус Мексиканский',
        slug: 'mexican_sause',
        price: 15,
        description: 'Гострий мексиканський соус з томатів і перцю чилі для любителів пікантного.',
        ingredients: ['Помідори', 'Перець чилі', 'Цибуля', 'Часник', 'Сіль', 'Спеції'],
        weight: 50,
        ccal: 90,
        preview: '/img/products/souses/meksika_BIG.jpg',
        product: '/img/products/souses/meksika_BIG.jpg',
      },
      {
        id: 5,
        title: 'Пікантний соус',
        slug: 'pikantniy_sause',
        price: 10,
        description: 'Соус середньої гостроти з томатів та спецій, підкреслює смак страв.',
        ingredients: ['Помідори', 'Перець', 'Цибуля', 'Часник', 'Спеції'],
        weight: 50,
        ccal: 85,
        preview: '/img/products/souses/pikantnyj_category.jpg',
        product: '/img/products/souses/pikantnyj_category.jpg',
      },
      {
        id: 6,
        title: 'Сироп Асорті',
        slug: 'syrop',
        price: 12,
        description: 'Солодкий сироп для десертів і напоїв, асорті смаків.',
        ingredients: ['Цукор', 'Вода', 'Сироп фруктовий', 'Ароматизатори'],
        weight: 50,
        ccal: 150,
        preview: '/img/products/souses/sirop-ass_category_new.jpg',
        product: '/img/products/souses/sirop-ass_category_new.jpg',
      },
      {
        id: 7,
        title: 'Сметана',
        slug: 'sour_cream',
        price: 8,
        description: 'Натуральна сметана, м’яка та ніжна, ідеальна для соусів і заправок.',
        ingredients: ['Вершки', 'Молочна закваска'],
        weight: 50,
        ccal: 120,
        preview: '/img/products/souses/smetana.jpg',
        product: '/img/products/souses/smetana.jpg',
      },
      {
        id: 8,
        title: 'Сирний соус',
        slug: 'cheese_sause',
        price: 10,
        description: 'Ніжний соус на основі сиру, ідеально пасує до картоплі та м’яса.',
        ingredients: ['Сир', 'Вершки', 'Масло', 'Спеції'],
        weight: 50,
        ccal: 150,
        preview: '/img/products/souses/sous-cheese_category.jpg',
        product: '/img/products/souses/sous-cheese_category.jpg',
      },
      {
        id: 9,
        title: 'Соус кисло-солодка',
        slug: 'sweet&sour_sause',
        price: 12,
        description:
          'Солодко-кислий соус з легким гострим відтінком, підходить до м’яса та закусок.',
        ingredients: ['Цукор', 'Оцет', 'Помідори', 'Перець', 'Спеції'],
        weight: 50,
        ccal: 90,
        preview: '/img/products/souses/soys-kislo-sladkij-chilli_category_new.jpg',
        product: '/img/products/souses/soys-kislo-sladkij-chilli_category_new.jpg',
      },
      {
        id: 10,
        title: 'Соус малина',
        slug: 'raspberry_sause',
        price: 12,
        description: 'Солодкий фруктовий соус з малини, ідеально підходить до десертів і млинців.',
        ingredients: ['Малина', 'Цукор', 'Вода', 'Лимонний сік'],
        weight: 50,
        ccal: 110,
        preview: '/img/products/souses/soys-malina_category_new.jpg',
        product: '/img/products/souses/soys-malina_category_new.jpg',
      },
    ],
  },
  {
    id: 6,
    title: 'Випiчка',
    href: '/bakery',
    slug: 'bakery',
    description: 'Свiжа випiчка від BUFET',
    products: [
      {
        id: 1,
        title: 'Сухарики',
        slug: 'croutons',
        price: 3,
        description: 'Хрусткі сухарики, ідеальні до супів та салатів.',
        ingredients: ['Борошно', 'Вода', 'Дріжджі', 'Сіль', 'Спеції'],
        weight: 30,
        ccal: 120,
        preview: '/img/products/breads/suchari_category.jpg',
        product: '/img/products/breads/suchari_category.jpg',
      },
      {
        id: 2,
        title: 'Сирники',
        slug: 'syrniki',
        price: 60,
        description: 'Смачні та ніжні сирники з домашнього сиру, пасують до меду чи сметани.',
        ingredients: ['Творог', 'Яйця', 'Цукор', 'Борошно', 'Ваніль'],
        weight: 150,
        ccal: 280,
        preview: '/img/products/breads/syrnike_category.jpg',
        product: '/img/products/breads/syrnike_category.jpg',
      },
      {
        id: 3,
        title: 'Кекс шоколадний',
        slug: 'capcake_chokolad',
        price: 30,
        description: 'Ніжний шоколадний кекс з ароматом какао, ідеальний до кави.',
        ingredients: ['Борошно', 'Яйця', 'Цукор', 'Какао', 'Масло'],
        weight: 120,
        ccal: 350,
        preview: '/img/products/breads/keks_shokolad.jpg',
        product: '/img/products/breads/keks_shokolad.jpg',
      },
      {
        id: 4,
        title: 'Кекс ванiльний',
        slug: 'cupcake_vanilla',
        price: 30,
        description: 'Легкий ванільний кекс з ароматом ванілі, м’який та повітряний.',
        ingredients: ['Борошно', 'Яйця', 'Цукор', 'Ваніль', 'Масло'],
        weight: 120,
        ccal: 340,
        preview: '/img/products/breads/keks-beliy.jpg',
        product: '/img/products/breads/keks-beliy.jpg',
      },
      {
        id: 5,
        title: 'Чiзкейк',
        slug: 'cheese_cake',
        price: 55,
        description: 'Ніжний класичний чізкейк з сирною основою на пісочному коржі.',
        ingredients: ['Творог', 'Яйця', 'Цукор', 'Вершкове масло', 'Пісочне тісто'],
        weight: 150,
        ccal: 380,
        preview: '/img/products/breads/cheese-cake-category.jpg',
        product: '/img/products/breads/cheese-cake-category.jpg',
      },
      {
        id: 6,
        title: 'Пирiг Пicочний',
        slug: 'pie',
        price: 35,
        description: 'Пісочний пиріг з ніжною начинкою, смачний до чаю або кави.',
        ingredients: ['Борошно', 'Масло', 'Яйця', 'Цукор', 'Начинка за вибором'],
        weight: 130,
        ccal: 320,
        preview: '/img/products/breads/pirog-pisochniy.jpg',
        product: '/img/products/breads/pirog-pisochniy.jpg',
      },
      {
        id: 7,
        title: 'Хлiб',
        slug: 'bread',
        price: 5,
        description: 'Свіжий хліб із натуральних інгредієнтів, випечений за класичною рецептурою.',
        ingredients: ['Борошно', 'Вода', 'Дріжджі', 'Сіль'],
        weight: 500,
        ccal: 1200,
        preview: '/img/products/breads/2.jpg',
        product: '/img/products/breads/2.jpg',
      },
    ],
  },
  {
    id: 7,
    title: 'Десерти',
    href: '/desserts',
    slug: 'desserts',
    description: 'Смачнi десерти вiд BUFET',
    products: [
      {
        id: 1,
        title: 'Морозиво в асортиментi',
        slug: 'ice_cream',
        price: 90,
        description:
          'Смачне морозиво різних смаків, ніжне та кремове, ідеальне для спекотного дня.',
        ingredients: ['Молоко', 'Вершки', 'Цукор', 'Ароматизатори', 'Барвники'],
        weight: 120,
        ccal: 250,
        preview: '/img/products/desserts/morozywo_category.jpg',
        product: '/img/products/desserts/morozywo_category.jpg',
      },
      {
        id: 2,
        title: 'Донат полуниця',
        slug: 'donut_strawberry',
        price: 40,
        description: 'Ніжний пончик з начинкою зі свіжої полуниці та глазур’ю.',
        ingredients: ['Борошно', 'Яйця', 'Цукор', 'Полуничне пюре', 'Масло'],
        weight: 80,
        ccal: 280,
        preview: '/img/products/desserts/donats-sho_category_new.jpg',
        product: '/img/products/desserts/donats-sho_category_new.jpg',
      },
      {
        id: 3,
        title: 'Донат шоколад',
        slug: 'donut_chokolate',
        price: 40,
        description: 'Солодкий шоколадний пончик з ніжною глазур’ю.',
        ingredients: ['Борошно', 'Яйця', 'Цукор', 'Какао', 'Масло'],
        weight: 80,
        ccal: 300,
        preview: '/img/products/desserts/donats-st_category_new.jpg',
        product: '/img/products/desserts/donats-st_category_new.jpg',
      },
      {
        id: 4,
        title: 'Панна котта',
        slug: 'pannakota',
        price: 50,
        description: 'Італійський десерт з вершків та желатину з ніжним смаком ванілі.',
        ingredients: ['Вершки', 'Цукор', 'Желатин', 'Ваніль', 'Сироп для подачі'],
        weight: 100,
        ccal: 220,
        preview: '/img/products/desserts/b131f584-80c7-4914-b4f5-970a6b173442.jpg',
        product: '/img/products/desserts/b131f584-80c7-4914-b4f5-970a6b173442.jpg',
      },
      {
        id: 5,
        title: 'Десерт Желе ананасове',
        slug: 'pineapple_jelly',
        price: 40,
        description: 'Легке желе з соком ананаса, освіжаючий десерт для будь-якого настрою.',
        ingredients: ['Сік ананаса', 'Цукор', 'Желатин', 'Вода'],
        weight: 90,
        ccal: 180,
        preview: '/img/products/desserts/Jele.jpg',
        product: '/img/products/desserts/Jele.jpg',
      },
    ],
  },
  {
    id: 8,
    title: 'Гарячi напоi',
    href: '/hot_drinks',
    slug: 'hot_drinks',
    description: 'Широкий асортимент гарячих напоїв від BUFET',
    products: [
      {
        id: 1,
        title: 'Кава Aйс Латте',
        slug: 'ice_latte',
        price: 50,
        description: 'Освіжаючий холодний латте з еспресо та молоком.',
        ingredients: ['Еспресо', 'Молоко', 'Лід', 'Сироп (за бажанням)'],
        weight: 300,
        ccal: 120,
        preview: '/img/products/hot-drinks/ice_latte_category.jpg',
        product: '/img/products/hot-drinks/ice_latte_category.jpg',
      },
      {
        id: 2,
        title: 'Ягiдний напiй Чорна смородина',
        slug: 'blackberry_drink',
        price: 40,
        description: 'Свіжий ягідний напій із чорної смородини, освіжаючий та корисний.',
        ingredients: ['Сік чорної смородини', 'Вода', 'Цукор', 'Лід'],
        weight: 250,
        ccal: 80,
        preview: '/img/products/hot-drinks/smorodina1.jpg',
        product: '/img/products/hot-drinks/smorodina1.jpg',
      },
      {
        id: 3,
        title: 'Ягiдний напiй Малиновий',
        slug: 'raspberry_drink',
        price: 40,
        description: 'Соковитий напій зі свіжої малини, солодкий і освіжаючий.',
        ingredients: ['Сік малини', 'Вода', 'Цукор', 'Лід'],
        weight: 250,
        ccal: 80,
        preview: '/img/products/hot-drinks/malina-category.jpg',
        product: '/img/products/hot-drinks/malina-category.jpg',
      },
      {
        id: 4,
        title: 'Ягiдний напiй Облепiховий',
        slug: 'sea_buckhorn_drink',
        price: 40,
        description: 'Корисний напій з обліпихи з яскравим кисло-солодким смаком.',
        ingredients: ['Сік обліпихи', 'Вода', 'Цукор', 'Лід'],
        weight: 250,
        ccal: 90,
        preview: '/img/products/hot-drinks/oblepiha-category.jpg',
        product: '/img/products/hot-drinks/oblepiha-category.jpg',
      },
      {
        id: 5,
        title: 'Мега Латте',
        slug: 'latte_xxl',
        price: 55,
        description: 'Подвійний латте з молоком та еспресо, ідеальний для зарядки енергією.',
        ingredients: ['Еспресо', 'Молоко', 'Сироп (за бажанням)'],
        weight: 400,
        ccal: 180,
        preview: '/img/products/hot-drinks/megaLatte_category.jpg',
        product: '/img/products/hot-drinks/megaLatte_category.jpg',
      },
      {
        id: 6,
        title: 'Какао з молоком',
        slug: 'cocoa',
        price: 45,
        description: 'Теплий какао напій з молоком, ідеальний для затишного вечора.',
        ingredients: ['Какао-порошок', 'Молоко', 'Цукор', 'Вершки (за бажанням)'],
        weight: 300,
        ccal: 200,
        preview: '/img/products/hot-drinks/cacao_category.jpg',
        product: '/img/products/hot-drinks/cacao_category.jpg',
      },
      {
        id: 7,
        title: 'Кава Шокната Лонг',
        slug: 'shoknata',
        price: 50,
        description: 'Насичена кава з шоколадними нотками та подовженим еспресо.',
        ingredients: ['Еспресо', 'Молоко', 'Шоколадний сироп', 'Лід (за бажанням)'],
        weight: 350,
        ccal: 150,
        preview: '/img/products/hot-drinks/americano_m_category.jpg',
        product: '/img/products/hot-drinks/americano_m_category.jpg',
      },
      {
        id: 8,
        title: 'Чай Ромашка',
        slug: 'chamomile_tea',
        price: 20,
        description: 'Заспокійливий трав’яний чай із квітів ромашки.',
        ingredients: ['Ромашка', 'Вода', 'Мед (за бажанням)'],
        weight: 250,
        ccal: 5,
        preview: '/img/products/hot-drinks/romaska_category_new.jpg',
        product: '/img/products/hot-drinks/romaska_category_new.jpg',
      },
      {
        id: 9,
        title: 'Чай Мелiса',
        slug: 'melisa_tea',
        price: 20,
        description: 'Ароматний чай із листя меліси для спокою та релаксу.',
        ingredients: ['Листя меліси', 'Вода', 'Мед (за бажанням)'],
        weight: 250,
        ccal: 5,
        preview: '/img/products/hot-drinks/melisa_category.jpg',
        product: '/img/products/hot-drinks/melisa_category.jpg',
      },
      {
        id: 10,
        title: 'Чай Малина',
        slug: 'raspberry_tea',
        price: 20,
        description: 'Чай із додаванням ягід малини для приємного солодкого смаку.',
        ingredients: ['Сушена малина', 'Вода', 'Мед (за бажанням)'],
        weight: 250,
        ccal: 5,
        preview: '/img/products/hot-drinks/tea_malina_category.jpg',
        product: '/img/products/hot-drinks/tea_malina_category.jpg',
      },
      {
        id: 11,
        title: 'Чай чорний',
        slug: 'black_tea',
        price: 20,
        description: 'Класичний чорний чай з насиченим смаком та ароматом.',
        ingredients: ['Чорний чай', 'Вода', 'Цукор/Мед (за бажанням)'],
        weight: 250,
        ccal: 5,
        preview: '/img/products/hot-drinks/tea_black_category.jpg',
        product: '/img/products/hot-drinks/tea_black_category.jpg',
      },
      {
        id: 12,
        title: 'Чай зелений',
        slug: 'green_tea',
        price: 20,
        description: 'Зелений чай для тонізуючого та освіжаючого ефекту.',
        ingredients: ['Зелений чай', 'Вода', 'Мед (за бажанням)'],
        weight: 250,
        ccal: 5,
        preview: '/img/products/hot-drinks/tea_green_category.jpg',
        product: '/img/products/hot-drinks/tea_green_category.jpg',
      },
      {
        id: 13,
        title: 'Кава натуральна Американо',
        slug: 'americano',
        price: 40,
        description:
          'Класичне еспресо, розбавлене гарячою водою, насичений смак без зайвої гіркоти.',
        ingredients: ['Еспресо', 'Гаряча вода'],
        weight: 250,
        ccal: 10,
        preview: '/img/products/hot-drinks/americano_category.jpg',
        product: '/img/products/hot-drinks/americano_category.jpg',
      },
      {
        id: 14,
        title: 'Кава натуральна Американо Лунго',
        slug: 'americano_lungo',
        price: 45,
        description: 'Подовжений американо для тих, хто любить тривалий смак кави.',
        ingredients: ['Еспресо', 'Гаряча вода'],
        weight: 300,
        ccal: 15,
        preview: '/img/products/hot-drinks/category-late-lungo.jpg',
        product: '/img/products/hot-drinks/category-late-lungo.jpg',
      },
      {
        id: 15,
        title: 'Кава натуральна Капучiно',
        slug: 'cuppucchino',
        price: 45,
        description: 'Класичний капучіно з еспресо, молоком та ніжною піною.',
        ingredients: ['Еспресо', 'Молоко', 'Піна'],
        weight: 250,
        ccal: 120,
        preview: '/img/products/hot-drinks/капучино_category.jpg',
        product: '/img/products/hot-drinks/капучино_category.jpg',
      },
      {
        id: 16,
        title: 'Кава натуральна Капучiно Лунго',
        slug: 'cappucchino-lungo',
        price: 50,
        description: 'Капучіно з більшою порцією еспресо та молока, ніж класичний.',
        ingredients: ['Еспресо', 'Молоко', 'Піна'],
        weight: 350,
        ccal: 150,
        preview: '/img/products/hot-drinks/капучино_м_category.jpg',
        product: '/img/products/hot-drinks/капучино_м_category.jpg',
      },
      {
        id: 17,
        title: 'Лате',
        slug: 'latte',
        price: 50,
        description: 'М’який латте з гарячим молоком та еспресо, класика кав’ярень.',
        ingredients: ['Еспресо', 'Молоко', 'Піна'],
        weight: 300,
        ccal: 140,
        preview: '/img/products/hot-drinks/category-late.jpg',
        product: '/img/products/hot-drinks/category-late.jpg',
      },
    ],
  },
  {
    id: 9,
    title: 'Холоднi напоi',
    href: '/cold_drinks',
    slug: 'cold_drinks',
    description: 'Освіжаючі напої на будь-який смак від BUFET',
    products: [
      {
        id: 1,
        title: 'Бонаква',
        slug: 'bonaqua',
        price: 20,
        description: 'Мінеральна вода без газу для щоденного споживання.',
        ingredients: ['Вода мінеральна'],
        weight: 500,
        ccal: 0,
        preview: '/img/products/cold-drinks/bonakva.jpg',
        product: '/img/products/cold-drinks/bonakva.jpg',
      },
      {
        id: 2,
        title: 'Кола',
        slug: 'coca_cola',
        price: 20,
        description: 'Класична солодка газована Кока-Кола.',
        ingredients: ['Вода газована', 'Цукор', 'Ароматизатори', 'Кофеїн'],
        weight: 330,
        ccal: 140,
        preview: '/img/products/cold-drinks/cola_category_repl.jpg',
        product: '/img/products/cold-drinks/cola_category_repl.jpg',
      },
      {
        id: 3,
        title: 'Кола zero',
        slug: 'cola_zero',
        price: 20,
        description: 'Класична Кока-Кола без цукру, з нульовою калорійністю.',
        ingredients: ['Вода газована', 'Підсолоджувачі', 'Ароматизатори', 'Кофеїн'],
        weight: 330,
        ccal: 0,
        preview: '/img/products/cold-drinks/cola_zero_category.jpg',
        product: '/img/products/cold-drinks/cola_zero_category.jpg',
      },
      {
        id: 4,
        title: 'Фанта',
        slug: 'fanta',
        price: 20,
        description: 'Апельсиновий газований напій із свіжим фруктовим смаком.',
        ingredients: ['Вода газована', 'Цукор', 'Апельсиновий концентрат', 'Ароматизатори'],
        weight: 330,
        ccal: 150,
        preview: '/img/products/cold-drinks/fanta_category.jpg',
        product: '/img/products/cold-drinks/fanta_category.jpg',
      },
      {
        id: 5,
        title: 'Мультифрут',
        slug: 'fruit_juice',
        price: 25,
        description: 'Свіжовичавлений фруктовий сік зі змішаних фруктів.',
        ingredients: ['Сік яблука', 'Сік апельсина', 'Сік ананаса', 'Сік маракуї'],
        weight: 300,
        ccal: 120,
        preview: '/img/products/cold-drinks/Multifruits_category.jpg',
        product: '/img/products/cold-drinks/Multifruits_category.jpg',
      },
      {
        id: 6,
        title: 'Сік апельсиновий малий',
        slug: 'orange_juice',
        price: 30,
        description: 'Свіжий апельсиновий сік, багатий на вітамін C.',
        ingredients: ['Апельсиновий сік'],
        weight: 250,
        ccal: 110,
        preview: '/img/products/cold-drinks/apelsinoviy_sok_m_category.jpg',
        product: '/img/products/cold-drinks/apelsinoviy_sok_m_category.jpg',
      },
      {
        id: 7,
        title: 'Сік апельсиновий великий',
        slug: 'orange_juice_xl',
        price: 35,
        description: 'Свіжий апельсиновий сік у великій порції.',
        ingredients: ['Апельсиновий сік'],
        weight: 400,
        ccal: 180,
        preview: '/img/products/cold-drinks/apelsinoviy_sok_b_category.jpg',
        product: '/img/products/cold-drinks/apelsinoviy_sok_b_category.jpg',
      },
      {
        id: 8,
        title: 'Сік томатний малий',
        slug: 'tomato_juice',
        price: 30,
        description: 'Свіжий томатний сік, ідеальний для підбадьорення та смаку.',
        ingredients: ['Томатний сік'],
        weight: 250,
        ccal: 30,
        preview: '/img/products/cold-drinks/tomat_sok_m_category.jpg',
        product: '/img/products/cold-drinks/tomat_sok_m_category.jpg',
      },
      {
        id: 9,
        title: 'Сік томатний великий',
        slug: 'tomato_juice_xl',
        price: 35,
        description: 'Велика порція свіжого томатного соку.',
        ingredients: ['Томатний сік'],
        weight: 400,
        ccal: 50,
        preview: '/img/products/cold-drinks/tomat_sok_category.jpg',
        product: '/img/products/cold-drinks/tomat_sok_category.jpg',
      },
      {
        id: 10,
        title: 'Лимонад малий',
        slug: 'lemonage',
        price: 20,
        description: 'Освіжаючий лимонад із натурального соку лимона.',
        ingredients: ['Вода', 'Лимонний сік', 'Цукор', 'Лід'],
        weight: 250,
        ccal: 60,
        preview: '/img/products/cold-drinks/limonad_b_category.jpg',
        product: '/img/products/cold-drinks/limonad_b_category.jpg',
      },
      {
        id: 11,
        title: 'Лимонад великий',
        slug: 'lemonage_xl',
        price: 25,
        description: 'Велика порція освіжаючого лимонаду з натуральним смаком.',
        ingredients: ['Вода', 'Лимонний сік', 'Цукор', 'Лід'],
        weight: 400,
        ccal: 100,
        preview: '/img/products/cold-drinks/limonad_category.jpg',
        product: '/img/products/cold-drinks/limonad_category.jpg',
      },
      {
        id: 12,
        title: 'Fuzetea чорний',
        slug: 'fuzetea',
        price: 25,
        description: 'Освіжаючий чай Fuzetea чорний з натуральними ароматами.',
        ingredients: ['Чорний чай', 'Вода', 'Цукор', 'Лимонний ароматизатор'],
        weight: 330,
        ccal: 50,
        preview: '/img/products/cold-drinks/fuzetea_black_category_repl.jpg',
        product: '/img/products/cold-drinks/fuzetea_black_category_repl.jpg',
      },
      {
        id: 13,
        title: 'Fuzetea зелений',
        slug: 'fuzetea_green',
        price: 25,
        description: 'Освіжаючий зелений чай Fuzetea з натуральними ароматами.',
        ingredients: ['Зелений чай', 'Вода', 'Цукор', 'Лимонний ароматизатор'],
        weight: 330,
        ccal: 50,
        preview: '/img/products/cold-drinks/fuzetea_gr_category-1.jpg',
        product: '/img/products/cold-drinks/fuzetea_gr_category-1.jpg',
      },
      {
        id: 14,
        title: 'Ягідний напій',
        slug: 'berry_drink',
        price: 30,
        description: 'Смачний ягідний напій з міксу свіжих ягід.',
        ingredients: ['Сік ягід', 'Вода', 'Цукор', 'Лід'],
        weight: 300,
        ccal: 90,
        preview: '/img/products/cold-drinks/jagody_category.jpg',
        product: '/img/products/cold-drinks/jagody_category.jpg',
      },
      {
        id: 15,
        title: 'Джмiл',
        slug: 'dzhmil',
        price: 25,
        description: 'Солодкий освіжаючий напій для дітей та дорослих.',
        ingredients: ['Вода', 'Цукор', 'Ароматизатори', 'Лід'],
        weight: 330,
        ccal: 80,
        preview: '/img/products/cold-drinks/djmil_category.jpg',
        product: '/img/products/cold-drinks/djmil_category.jpg',
      },
      {
        id: 16,
        title: 'Sprite',
        slug: 'sprite',
        price: 25,
        description: 'Класичний безалкогольний лимонно-лаймовий напій.',
        ingredients: ['Вода газована', 'Цукор', 'Лимонний ароматизатор', 'Лайм'],
        weight: 330,
        ccal: 140,
        preview: '/img/products/cold-drinks/sprite_category.jpg',
        product: '/img/products/cold-drinks/sprite_category.jpg',
      },
    ],
  },
  {
    id: 10,
    title: 'Молочнi коктейлi',
    href: '/shakes',
    slug: 'shakes',
    description: 'Смачні молочні коктейлі з дитинства від BUFET',
    products: [
      {
        id: 1,
        title: 'Коктейль молочний',
        slug: 'shake',
        price: 40,
        description: 'Класичний молочний коктейль на свіжому молоці з вершками.',
        ingredients: ['Молоко', 'Вершки', 'Цукор', 'Ароматизатори'],
        weight: 300,
        ccal: 250,
        preview: '/img/products/milk-shakes/coctail_b_category.jpg',
        product: '/img/products/milk-shakes/coctail_b_category.jpg',
      },
      {
        id: 2,
        title: 'Коктейль банановий',
        slug: 'banana_shake',
        price: 45,
        description: 'Смачний банановий молочний коктейль із свіжим бананом і вершками.',
        ingredients: ['Молоко', 'Вершки', 'Банан', 'Цукор'],
        weight: 350,
        ccal: 280,
        preview: '/img/products/milk-shakes/coctail_b_category.jpg',
        product: '/img/products/milk-shakes/coctail_b_category.jpg',
      },
    ],
  },
];

export const cafes = [
  {
    id: 1,
    address: 'вул. 23 Серпня, 30',
    note: '2 хвилини від метро 23 Серпня',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0507196149',
    isOpen: true,
  },
  {
    id: 2,
    address: 'вул. Академіка Павлова, 120',
    note: '7 хвилин від метро Академіка Павлова',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0953691297',
    isOpen: true,
  },
  {
    id: 3,
    address: 'вул. Григорія Сковороди, 40',
    note: '3 хвилини від метро Архітектора Бекетова',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0508336796',
    isOpen: true,
  },
  {
    id: 4,
    address: 'пр. Незалежності, 5-А',
    note: '7 хвилин від метро Держпром',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0997630488',
    isOpen: true,
  },
  {
    id: 5,
    address: 'пр. Аерокосмічний, 177',
    note: 'район Одеська, навпроти Класу',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0958021478',
    isOpen: true,
  },
  {
    id: 6,
    address: 'пр. Любові Малої, 24',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0665349434',
    isOpen: true,
  },
  {
    id: 7,
    address: 'пр. Архітектора Альошина, 19',
    note: '15 хвилин від метро Тракторний завод',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0501398148',
    isOpen: true,
  },
  {
    id: 8,
    address: 'вул. Полтавський шлях, 126',
    note: '7 хвилин від метро Холодна Гора',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0660617361',
    isOpen: true,
  },
  {
    id: 9,
    address: 'вул. Культури, 23',
    note: '1 хвилина від метро Наукова',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0507727357',
    isOpen: true,
  },
  {
    id: 10,
    address: 'вул. Сумська, 41',
    note: '2 хвилини від метро Університет',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0991878310',
    isOpen: true,
  },
  {
    id: 11,
    address: 'просп. Героїв Харкова, 256-Б',
    note: '1 хвилина від метро Імені О.С. Масельського',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0955525703',
    isOpen: true,
  },
  {
    id: 12,
    address: 'пр. Науки, 38',
    note: '5 хвилин від метро Ботанічний сад',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0994209154',
    isOpen: true,
  },
  {
    id: 13,
    address: 'вул. Григорія Сковороди, 92/1',
    note: '5 хвилин від метро Ярослава Мудрого',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0992924517',
    isOpen: true,
  },
  {
    id: 14,
    address: 'вул. Валентинівська, 21',
    note: '3 хвилини від метро Студентська',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0662404807',
    isOpen: true,
  },
  {
    id: 15,
    address: 'Салтівське шосе, 262-Б',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0663245831',
    isOpen: true,
  },
  {
    id: 16,
    address: 'пров. Костюринський, 3',
    note: '10 хвилин від метро Площа Конституції',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: '+38 0951494758',
    isOpen: true,
  },
  {
    id: 17,
    address: 'вул. Чкалова, 2-Д',
    note: 'зупинка 12 тролейбуса',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: null,
    isOpen: false,
  },
  {
    id: 18,
    address: 'вул. Леся Сердюка, 44',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: null,
    isOpen: false,
  },
  {
    id: 19,
    address: 'вул. Холодногірська, 2А',
    note: 'ринок Казка',
    workTime: { monSat: '8:00-21:00', sun: '9:00-21:00' },
    phone: null,
    isOpen: false,
  },
];

export const videos = [
  {
    id: 1,
    title: 'Акція від ТМ «Буфет»',
    src: 'https://www.youtube.com/embed/3ENbcCLwbiY',
    width: 730,
    height: 410,
  },
  {
    id: 2,
    title: 'Акція від ТМ «Буфет»',
    src: 'https://www.youtube.com/embed/3ENbcCLwbiY',
    width: 730,
    height: 410,
  },
  {
    id: 3,
    title: 'Вместе веселей! «Буфет» так быстро и так вкусно!',
    src: 'https://www.youtube.com/embed/u8ZMuCSkNpk',
    width: 730,
    height: 410,
  },
  {
    id: 4,
    title: 'Пицца в «Буфет»',
    src: 'https://www.youtube.com/embed/T-RzCZTuWyA',
    width: 730,
    height: 410,
  },
  {
    id: 5,
    title: '«Буфет»',
    src: 'https://www.youtube.com/embed/wS5EHc9jTIU',
    width: 730,
    height: 410,
  },
  {
    id: 6,
    title: '«Буфет» работает всегда!',
    src: 'https://www.youtube.com/embed/gpD91KXlzCY',
    width: 730,
    height: 410,
  },
  {
    id: 7,
    title: 'Квесты с призами от сети кафе «Буфет» и квест-комнаты «Внутри»!',
    src: 'https://www.youtube.com/embed/4mv6up3qK5Q',
    width: 730,
    height: 410,
  },
  {
    id: 8,
    title: 'Солодке побачення',
    src: 'https://www.youtube.com/embed/GFUwjqi43M4',
    width: 730,
    height: 410,
  },
];

export const principles = [
  { id: 1, text: 'Постійний розвиток і вдосконалення.' },
  { id: 2, text: 'Відповідальне ставлення до всього, що ми робимо.' },
  { id: 3, text: 'Дотримання високих стандартів якості приготування страв та обслуговування.' },
  { id: 4, text: 'Швидке та якісне обслуговування.' },
  { id: 5, text: 'Послуга попереднього замовлення.' },
  { id: 6, text: 'Точне виконання замовлення.' },
  { id: 7, text: 'Ввічливість, увага, дружелюбність і посмішка.' },
  { id: 8, text: 'Чистота та акуратність.' },
  { id: 9, text: 'Цілодобова робота.' },
  { id: 10, text: 'Використовуємо місцеві традиційні продукти харчування.' },
  {
    id: 11,
    text: 'Можливість звернення до «Журналу відгуків і пропозицій» або на сайт мережі BUFET.',
  },
];

export const benefits = [
  { id: 1, text: 'Стабільна щотижнева оплата (ставка + бонуси).' },
  { id: 2, text: 'Оплачуване стажування.' },
  {
    id: 3,
    text: 'Можливість кар’єрного зростання: більшість наших керівників починали з бармена або кухаря.',
  },
  { id: 4, text: 'Безкоштовна уніформа.' },
  { id: 5, text: 'Знижки на продукцію BUFET.' },
  { id: 6, text: 'Навчальні тренінги.' },
  { id: 7, text: 'Корпоративні заходи та подарунки на свята.' },
  { id: 8, text: 'Знижка 10% на медичне обслуговування в ОН Клінік Харків.' },
  { id: 9, text: 'У нас є чай з печеньками.' },
  { id: 10, text: 'У нас немає штрафів — є тільки бонуси!' },
];

export const facilities = [
  {
    id: 1,
    text: 'У кожному BUFET є генератор, тому ми працюємо завжди, навіть при відключеннях світла.',
  },
  {
    id: 2,
    text: 'Ми завжди на зв’язку. Внутрішний Wi-fi працює для усіх співробітників весь час.',
  },
  { id: 3, text: 'Кондиціонери є і в залі для гостей, і на кухні для співробітників.' },
  {
    id: 4,
    text: 'Сучасні пароконвектомати UNOX і RATIONAL з автоматичною мийкою для зручності кухарів.',
  },
  { id: 5, text: 'Потужні системи вентиляції — дихаємо свіжим повітрям.' },
  { id: 6, text: 'Система фільтрації води (зворотний осмос) — п’ємо лише чисту воду.' },
  {
    id: 7,
    text: 'У нас завжди чисто — щоденне прибирання з використанням професійних миючих засобів.',
  },
  { id: 8, text: 'У нас є кіоски самообслуговування для гостей.' },
];

export const requreties = [
  { id: 1, text: 'Довіра, чесність, взаємодопомога.' },
  { id: 2, text: 'Довгострокове співробітництво на взаємовигідній основі.' },
  { id: 3, text: 'Встановлення дружніх контактів.' },
  { id: 4, text: 'Гнучкість у перемовинах.' },
  { id: 5, text: 'Обов’язковість і точність виконання домовленностей.' },
  { id: 6, text: 'Дотримання міжнародних норм ділової етики.' },
  { id: 7, text: 'Прозорість співробітництва.' },
];

export const suppliers_products = [
  { id: 1, text: 'Свіжі овочі і гриби.' },
  { id: 2, text: 'Молочні продукти та вироби, зокрема тверді сири.' },
  { id: 3, text: 'Кондитерські та пекарські вироби.' },
  { id: 4, text: 'Безалкогольні напої, соки, мінеральна вода, кава та чай.' },
  { id: 5, text: 'М’ясо охолоджене та м’ясні вироби, зокрема ковбаси.' },
  { id: 6, text: 'Бакалійні вироби, зокрема спеції, приправи і соуси.' },
  { id: 7, text: 'Консервація плодово-овочевої продукції.' },
  { id: 8, text: 'Супутні товари.' },
  { id: 9, text: 'Одноразовий посуд.' },
  { id: 10, text: 'Поліграфія.' },
  { id: 11, text: 'Послуги, що необхідні для роботи мережі піцерій.' },
];

export const suppliers_req = [
  { id: 1, text: 'Постачальникам, якість товарів яких вища, ніж у інших.' },
  { id: 2, text: 'Постачальникам, маркетинговий фонд яких вище, ніж у інших.' },
  { id: 3, text: 'Постачальникам, ціни яких нижче, ніж у інших.' },
  {
    id: 4,
    text: 'Постачальникам, які мають добре налагоджену службу доставки товарів до складів торговельної точки.',
  },
  { id: 5, text: 'Постачальникам, які мають сертифікати якості й безпеки.' },
  {
    id: 6,
    text: 'Постачальникам, які мають спеціалізований транспорт, де встановлено пристрої зчитування температури під час перевезення.',
  },
  { id: 7, text: 'Постачальникам, які надають найбільше відтермінування платежу.' },
  { id: 8, text: '«Старим» постачальникам, які мають рівні умови з новими постачальниками.' },
];
